Repository sg8541/millionvolt, pull requests merged in 2024-12, with the labels that each got.

#1 init: 새로운 프로젝트 생성
  .gitignore
  ifive/.gitattributes
  ifive/.gitignore
  ifive/build.gradle
  ifive/gradle/wrapper/gradle-wrapper.jar
  ifive/gradle/wrapper/gradle-wrapper.properties
  ifive/gradlew
  ifive/gradlew.bat
  ifive/settings.gradle
  ifive/src/main/java/kr/co/milionvolt/ifive/IfiveApplication.java
  ifive/src/main/resources/application.properties
  ifive/src/test/java/kr/co/milionvolt/ifive/IfiveApplicationTests.java
Labels: init

#3 Design: main page 1차 완료
  ifive/src/main/resources/templates/main.html
Labels: design

#4 design : 로그인 페이지, 회원가입 페이지, 아이디 찾기 페이지, 비밀번호 찾기 페이지 1차 구현
  ifive/src/main/resources/static/findID.html
  ifive/src/main/resources/static/findIDinfo.html
  ifive/src/main/resources/static/findPWD.html
  ifive/src/main/resources/static/findPWDEmail.html
  ifive/src/main/resources/static/images/EV6.PNG
  ifive/src/main/resources/static/images/modal-click.png
  ifive/src/main/resources/static/join.html
  ifive/src/main/resources/static/joininform.html
  ifive/src/main/resources/static/login.html
  ifive/src/main/resources/static/newpassword.html
  ifive/src/main/resources/static/register.html
Labels: enhancement, design

#8 Feat: charger, charging_station Mapper 및 MapperTest 작성
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/ChargerController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/MainController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/CarModelDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/CarModelVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/ChargerDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/ChargerVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/ChargingStationDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/ChargingStationVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/NotificationDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/NotificationVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/PaymentDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/PaymentVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/PenaltieDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/PenaltieVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/ReservationDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/ReservationVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/RoleDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/RoleVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/UserCarDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/UserCarVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/UserDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/UserVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/CarModelMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargerMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/NotificationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/PaymentMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/PenaltieMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ReservationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/RoleMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserCarMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/ChargerService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/ChargerServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/ChargingStationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/ChargingStationServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/UserService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/UserServiceImpl.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ChargerMapperTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapperTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/UserMapperTest.java
Labels: Feature

#7 feat: security 적용 및 회원가입(유저정보 가입, 내 차 정보 미구현) 구현
  ifive/src/main/java/kr/co/milionvolt/ifive/IfiveApplication.java
  ifive/src/main/java/kr/co/milionvolt/ifive/config/DataSourceConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/SignupController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/dto/user/SignupDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/mybatis/dao/SignupMapper.java
  ifive/src/main/resources/application.properties
Labels: enhancement

#9 Fix: 충돌 해결
  ifive/src/main/resources/templates/main.html
Labels: bug

#13 Feat: controller 1차 작업
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/ChargerController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/MainController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/charger/ChargerDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/charger/ChargerVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargingstation/ChargingStationDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargingstation/ChargingStationVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargerMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationServiceImpl.java
  ifive/src/main/resources/application.properties
  ifive/src/main/resources/static/findID.html
  ifive/src/main/resources/static/findIDinfo.html
  ifive/src/main/resources/static/findPWD.html
  ifive/src/main/resources/static/findPWDEmail.html
  ifive/src/main/resources/static/join.html
  ifive/src/main/resources/static/joininform.html
  ifive/src/main/resources/static/login.html
  ifive/src/main/resources/static/newpassword.html
  ifive/src/main/resources/templates/main.html
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ChargerMapperTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapperTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/service/ChargerServiceTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/service/ChargingStationServiceTest.java
Labels: Feature

#15 Chore: 누락된 파일 다시 올림
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  frontend/.vscode/extensions.json
  frontend/.vscode/settings.json
  frontend/src/views/pages/account-settings/AccountSettingsNotification.vue
  ifive/.gitignore
  ifive/src/main/java/kr/co/milionvolt/ifive/exception/SignupException.java
Labels: bug

#16 Fix: ChargingStationMapper 수정
  ifive/src/main/java/kr/co/milionvolt/ifive/config/AppConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/ChargerController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/MainController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/ChargingStationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargingstation/ChargingStationApiResponse.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/util/PublicApiClient.java
  ifive/src/main/resources/application.properties
  ifive/src/main/resources/templates/main.html
  ifive/src/test/java/kr/co/milionvolt/ifive/service/ChargerServiceTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/service/ChargingStationServiceTest.java
Labels: bug

#17 feat: 회원가입 자동차 정보까지 insert 되도록 기능 구현
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/UserInfoController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/user/PasswordDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/user/SignupDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/usercar/UserCarDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/CarBatteryAndChargerTypeUpdateDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/CarNumberAndModelUpdateDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/DashboardResponseDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserCarInfoDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserDashboradUserCarDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserInfoDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserInfoPaymentListVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserInfoReservationListVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/SignupMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/SignupServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserServiceImpl.java
  ifive/src/main/resources/application.properties
Labels: enhancement

#20 feat: 충전소 api 구현 중
  ifive/build.gradle
  ifive/src/main/java/kr/co/milionvolt/ifive/config/AppConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargingstation/ChargingStationApiResponse.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargingstation/ChargingStationDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargingstation/ChargingStationVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargerMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/util/PublicApiClient.java
  ifive/src/main/resources/application.properties
  ifive/src/main/resources/templates/main.html
  ifive/src/test/java/kr/co/milionvolt/ifive/service/ChargerServiceTest.java
Labels: Feature

#21 feat : 이용금 결제 API 구현, 예약 리스트 조회 및 예약 저장
  ifive/build.gradle
  ifive/src/main/java/kr/co/milionvolt/ifive/config/IamportConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/payment/PayPriceController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/reservation/ReservationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/reservation/ReservationListController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/payment/PayPriceDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/reservation/ReservationDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/reservation/ReservationListDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/PayPriceMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ReservationListMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ReservationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/payment/PayPriceService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/payment/PayPriceServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/reservation/ReservationListService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/reservation/ReservationListServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/reservation/ReservationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/reservation/ReservationServiceImpl.java
  ifive/src/main/resources/static/pay-deposit.html
  ifive/src/main/resources/static/pay-price.html
  ifive/src/main/resources/static/reserve.html
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/PayPriceTests.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ReservationListTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ReservationTest.java
Labels: enhancement

#24 Feat: JWT 토큰 구현, Redis Config 구현, 로그인 및 로그아웃 + 로그인 시 mypage 접속 가능
  .vscode/extensions.json
  .vscode/settings.json
  ifive/build.gradle
  ifive/src/main/java/kr/co/milionvolt/ifive/config/RedisConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/LoginAndLogoutController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/UserInfoController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/error/ApiError.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/token/TokenUserInfoDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/user/LoginDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/user/TokenResponseDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/user/UserDetailsVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/entity/RefreshTokenRedis.java
  ifive/src/main/java/kr/co/milionvolt/ifive/exception/GlobalExceptionHandler.java
  ifive/src/main/java/kr/co/milionvolt/ifive/exception/LoginException.java
  ifive/src/main/java/kr/co/milionvolt/ifive/exception/SignatureException.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/repository/RefreshTokenRepository.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/JwtAuthenticationFilter.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/JwtTokenProvider.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/CustomUserDetailsService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/LoginAndLogoutService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/LoginAndLogoutServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserServiceImpl.java
Labels: enhancement

#23 feat : 충전 상태페이지 정보 받아서 -> 결제페이지 이동 후 결제 확인
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/router/index.js
  frontend/src/stores/webSocketChargingStore.js
  frontend/src/views/chargingwebsocket/ChargingStatus.vue
  frontend/yarn.lock
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStatusMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/AlramWebSocketHandler.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapperTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/service/ChargingStationServiceTest.java
Labels: enhancement

#26 feat : PayPrice.vue ,TestAlarm.vue 추가
  frontend/src/views/alarm/TestAlarm.vue
  frontend/src/views/payment/PayPrice.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/repository/ReservationRepository.java
Labels: enhancement

#30 Feat: mainPage .html 적용중
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/csv/CsvToDtoConverter.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargeSpeed/chargeSpeedDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargeSpeed/chargeSpeedVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/charger/ChargerDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/charger/ChargerVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargerStatus/ChargerStatusDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargerStatus/ChargerStatusVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargingstation/ChargingStationDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/chargingstation/ChargingStationVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargerMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/CsvImportService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/CsvRunner.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationServiceImpl.java
  ifive/src/main/resources/data/charging_stations.csv
  ifive/src/main/resources/templates/main.html
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ChargerMapperTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapperTest.java
Labels: Feature

#33 Feat: 로그인 및 로그아웃, 마이페이지 대시보드 및 내정보 조회/수정 구현
  frontend/.vscode/extensions.json
  frontend/.vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/layouts/components/DefaultLayoutWithVerticalNav.vue
  frontend/src/pages/dashboard.vue
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/dashboard/AnalyticsCongratulations.vue
  frontend/src/views/dashboard/AnalyticsPaymentTable.vue
  frontend/src/views/dashboard/AnalyticsReservationTable.vue
  frontend/src/views/dashboard/AnalyticsTotalRevenue.vue
  frontend/src/views/pages/account-settings/AccountSettingsAccount.vue
  frontend/src/views/pages/user-account/Agreement.vue
  frontend/src/views/pages/user-account/FindByUserId.vue
  frontend/src/views/pages/user-account/Login.vue
  frontend/src/views/pages/user-account/Signup.vue
  frontend/yarn.lock
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/LoginAndLogoutController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/SignupController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/UserInfoController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/user/SignupDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/CarBatteryAndChargerSpeedUpdateDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/DashboardResponseDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UpdateUserInfoDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserDashboradChartDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserDashboradUserCarDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserInfoPaymentListVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserInfoReservationListVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/SignupMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/CsvImportService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/CsvRunner.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/CustomUserDetailsService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/SignupServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserServiceImpl.java
  package-lock.json
Labels: enhancement

#38 Feat: 유저acount 관련 페이지 vue 전환 및 기능 구현
  .gitignore
  frontend/src/pages/my-payment.vue
  frontend/src/pages/my-reservation.vue
  frontend/src/router/index.js
  frontend/src/views/pages/account-settings/AccountSettingsAccount.vue
  frontend/src/views/pages/account-settings/AccountSettingsNotification.vue
  frontend/src/views/pages/account-settings/AccountSettingsSecurity.vue
  frontend/src/views/pages/tables/PaymentTable.vue
  frontend/src/views/pages/tables/ReservationTable.vue
  frontend/src/views/pages/user-account/ExitUser.vue
  frontend/src/views/pages/user-account/FindByUserId.vue
  frontend/src/views/pages/user-account/FindIDResult.vue
  frontend/src/views/pages/user-account/FindPWDEmail.vue
  frontend/src/views/pages/user-account/FindPassword.vue
  frontend/src/views/pages/user-account/Login.vue
  frontend/src/views/pages/user-account/NewPassword.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/SignupController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/UserController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/UserInfoController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserCarInfoDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/SignupMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/SignupService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/SignupServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserServiceImpl.java
Labels: enhancement

#39 Feat: 메인 최종-1(사이드바, 충전소마커, 충전소 모달, 알림창 위치 구현)
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/vue.config.js
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/csv/CsvToDtoConverter.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargerMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationServiceImpl.java
  ifive/src/main/resources/data/charging_stations.csv
  ifive/src/main/resources/templates/main.html
Labels: Feature

#40 Feat: Vue 충전기 예약 상태 수정
  frontend/public/images/logo2.png
  frontend/src/api/chargingStations.js
  frontend/src/components/Charger.vue
  frontend/src/components/Header.vue
  frontend/src/components/Map.vue
  frontend/src/components/Modal.vue
  frontend/src/components/Sidebar.vue
  frontend/src/router/index.js
  frontend/src/views/main/ChargingStationPage.vue
  frontend/src/views/payment/Reservation.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerServiceImpl.java
Labels: Feature

#42 Refactor: .env 수정으로 인한 관련 url 명 수정, package 프로젝트 명 수정
  frontend/package.json
  frontend/src/axios.js
Labels: enhancement

#43 Feat: 사이드바 구현 완료, 페이징처리 수정 예정
  frontend/src/components/Modal.vue
  frontend/src/components/Sidebar.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationServiceImpl.java
  ifive/src/main/resources/application.properties
Labels: Feature

#44 Feat: 메인 충전기 예약 버튼 클릭시 에러 수정
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
Labels: Feature

#45 Feat: 회원가입 시 유효성 검사 구현
  frontend/index.html
  frontend/src/views/pages/account-settings/AccountSettingsAccount.vue
  frontend/src/views/pages/account-settings/AccountSettingsNotification.vue
  frontend/src/views/pages/user-account/FindByUserId.vue
  frontend/src/views/pages/user-account/Signup.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/SignupController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/SignupMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/SignupService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/SignupServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserServiceImpl.java
Labels: enhancement

#46 feat : header에 알림창 구현 및 충전기 상태 실시간 업데이트 구현
  frontend/package-lock.json
  frontend/src/components/Header.vue
  frontend/src/components/Modal.vue
  frontend/src/stores/webSocketAlarmStore.js
  frontend/src/stores/webSocketChargerChangeStore.js
  frontend/src/stores/webSocketChargingStore.js
  frontend/src/views/chargingwebsocket/ChargingStatus.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/ChargingStatusController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/penaltie/PenaltieDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/penaltie/PenaltiechargerStatusCheckVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/penaltie/PenaltyCheckVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/entity/ReservationRedis.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStatusMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/PenaltyMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charging/ChargingStatusSerivce.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charging/ChargingStatusServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/penalty/PenaltyService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/penalty/PenaltyServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/reservation/ReservationServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/AlarmWebSocketHandler.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/ChargingWebSocketHandler.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/WebSocketConfig.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/ChargingStatusMapperTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/PenaltyChargerTest.java
  ifive/src/test/java/kr/co/milionvolt/ifive/service/ChargingStatusService.java
Labels: enhancement

#47 Style: 페이지상단에 올라가 있던 것들을 중심으로 통일
  frontend/public/favicon.ico
  frontend/src/assets/images/12/logo.svg
  frontend/src/assets/images/logo copy 2.svg
  frontend/src/assets/images/logo copy.svg
  frontend/src/assets/images/logo.svg
  frontend/src/assets/images/logo/logo-black-white.png
  frontend/src/assets/images/logo/logo-black-white2.png
  frontend/src/assets/images/logo/logo-black.png
  frontend/src/assets/images/logo/logo-black2.png
  frontend/src/assets/images/logo/logo-white-black.png
  frontend/src/assets/images/logo/logo-white-black2.png
  frontend/src/assets/images/logo/logo-white.png
  frontend/src/assets/images/logo/logo-white2.png
  frontend/src/assets/images/logo/logo-yellow-black.png
  frontend/src/assets/images/logo/logo-yellow-black2.png
  frontend/src/assets/images/logo/logo-yellow-white.png
  frontend/src/assets/images/logo/logo-yellow-white2.png
  frontend/src/assets/logo.svg
  frontend/src/components/Header.vue
  frontend/src/views/pages/user-account/FindByUserId.vue
  frontend/src/views/pages/user-account/FindIDResult.vue
  frontend/src/views/pages/user-account/FindPWDEmail.vue
  frontend/src/views/pages/user-account/FindPassword.vue
  frontend/src/views/pages/user-account/Login.vue
  frontend/src/views/pages/user-account/NewPassword.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
Labels: design

#48 Feat: 메인 페이지 페이징처리 완료, 사이드바 사용가능한 충전기 개수 수정 예정
  frontend/public/images/user-location-icon.png
  frontend/src/components/Header.vue
  frontend/src/components/Map.vue
  frontend/src/components/Modal.vue
  frontend/src/components/Sidebar.vue
  frontend/src/router/index.js
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charger/ChargerServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/chargingstation/ChargingStationServiceImpl.java
Labels: Feature

#51 Feat: 메인 최종 (더미데이터 및 헤더 넣으면 완료)
  frontend/package-lock.json
  frontend/src/components/Header.vue
  frontend/src/components/Sidebar.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/main/ChargingStationController.java
Labels: Feature

#54 Style: 유저 관련페이지(로그인 등)와 결제 및 예약 페이지 CSS 수정
  frontend/src/views/pages/user-account/FindByUserId.vue
  frontend/src/views/pages/user-account/FindIDResult.vue
  frontend/src/views/pages/user-account/FindPWDEmail.vue
  frontend/src/views/pages/user-account/FindPassword.vue
  frontend/src/views/pages/user-account/Login.vue
  frontend/src/views/pages/user-account/NewPassword.vue
  frontend/src/views/payment/PayPrice.vue
  frontend/src/views/payment/Reservation.vue
Labels: design

#53 fix : 충전기 실시간 상태변화 STOMP 방식에서 WebSocket 방식으로 전환
  frontend/src/components/Modal.vue
  frontend/src/stores/stompChagerStateStore.js
  frontend/src/stores/webSocketChargerChangeStore.js
  frontend/src/views/chargingwebsocket/ChargerChangeState.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/service/charging/ChargingStatusServiceImpl.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/ChargeStateChangeWebSocketHandler.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/ChargingWebSocketHandler.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/WebSocketConfig.java
Labels: enhancement

#55 fix: 이메일 중복 찾기 예외 처리 수정 및 주석제거
  frontend/src/views/pages/account-settings/AccountSettingsAccount.vue
  frontend/src/views/payment/PayPrice.vue
  frontend/src/views/payment/Reservation.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/PayPriceMapper.java
Labels: bug, enhancement

#56 Fix: 로그인 로그아웃 시 헤더 변경 및 css 수정
  frontend/src/@core/scss/base/_components.scss
  frontend/src/@core/scss/template/_vertical-nav.scss
  frontend/src/@core/scss/template/placeholders/_nav.scss
  frontend/src/components/Header.vue
  frontend/src/layouts/components/DefaultLayoutWithVerticalNav.vue
  frontend/src/pages/account-settings.vue
  frontend/src/pages/dashboard.vue
  frontend/src/plugins/vuetify/theme.js
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/dashboard/AnalyticsCongratulations.vue
  frontend/src/views/pages/account-settings/AccountSettingsAccount.vue
  frontend/src/views/payment/PayPrice.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/UserInfoController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserServiceImpl.java
Labels: bug, enhancement, design

#58 Feat: 최종 메인 에러 수정 및 사이드바 수정
  ifive/src/main/java/kr/co/milionvolt/ifive/security/SecurityConfig.java
Labels: Feature

#64 Style: 사이드바 및 모달 버튼 색상 수정, 헤더 로고 및 크기 수정
  frontend/src/components/Header.vue
  frontend/src/components/Map.vue
  frontend/src/components/Modal.vue
  frontend/src/components/Sidebar.vue
Labels: design

#67 Fix: 숫자 아이디 로그인이 안되던 문제 해결, 비번에서 특수 문자 입력 시 회원가입 불가 해결
  frontend/src/pages/dashboard.vue
  frontend/src/stores/auth.js
  frontend/src/views/pages/user-account/Login.vue
  frontend/src/views/pages/user-account/NewPassword.vue
  frontend/src/views/pages/user-account/Signup.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/LoginAndLogoutController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/user/TokenResponseDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/user/UserDetailsVO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/security/JwtTokenProvider.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/LoginAndLogoutServiceImpl.java
Labels: bug

#70 Fix: 비밀번호 유효성 검사와 배터리 용량 단위 수정
  frontend/src/assets/images/pages/403.png
  frontend/src/components/Header.vue
  frontend/src/pages/dashboard.vue
  frontend/src/pages/forbidden.vue
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/dashboard/AnalyticsCongratulations.vue
  frontend/src/views/pages/user-account/Agreement.vue
  frontend/src/views/pages/user-account/FindByUserId.vue
  frontend/src/views/pages/user-account/FindPWDEmail.vue
  frontend/src/views/pages/user-account/NewPassword.vue
  frontend/src/views/pages/user-account/Signup.vue
Labels: bug

#71 Feat: 차 정보 수정, 회원탈퇴 구현
  frontend/src/assets/images/avatars/avatar-1.png
  frontend/src/assets/images/avatars/avatar-10.png
  frontend/src/assets/images/avatars/avatar-11.png
  frontend/src/assets/images/avatars/avatar-12.png
  frontend/src/assets/images/avatars/avatar-13.png
  frontend/src/assets/images/avatars/avatar-14.png
  frontend/src/assets/images/avatars/avatar-15.png
  frontend/src/assets/images/avatars/avatar-2.png
  frontend/src/assets/images/avatars/avatar-3.png
  frontend/src/assets/images/avatars/avatar-4.png
  frontend/src/assets/images/avatars/avatar-5.png
  frontend/src/assets/images/avatars/avatar-6.png
  frontend/src/assets/images/avatars/avatar-7.png
  frontend/src/assets/images/avatars/avatar-8.png
  frontend/src/assets/images/avatars/avatar-9.png
  frontend/src/assets/images/cards/illustration-john-dark.png
  frontend/src/assets/images/cards/illustration-john-light.png
  frontend/src/assets/images/eCommerce/2.png
  frontend/src/assets/images/icons/flags/australia.png
  frontend/src/assets/images/icons/flags/belgium.png
  frontend/src/assets/images/icons/flags/brazil.png
  frontend/src/assets/images/icons/flags/china.png
  frontend/src/assets/images/icons/flags/france.png
  frontend/src/assets/images/icons/flags/india.png
  frontend/src/assets/images/icons/flags/usa.png
  frontend/src/assets/images/pages/1.png
  frontend/src/assets/images/pages/2.png
  frontend/src/assets/images/pages/3.png
  frontend/src/assets/images/pages/5.jpg
  frontend/src/assets/images/pages/6.jpg
  frontend/src/assets/images/pro/upgrade-banner-dark.png
  frontend/src/assets/images/pro/upgrade-banner-light.png
  frontend/src/layouts/components/DefaultLayoutWithVerticalNav.vue
  frontend/src/pages/account-settings.vue
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/pages/account-settings/AccountSettingsAccount.vue
  frontend/src/views/pages/account-settings/AccountSettingsCar.vue
  frontend/src/views/pages/account-settings/AccountSettingsNotification.vue
  frontend/src/views/pages/account-settings/AccountSettingsSecurity.vue
  frontend/src/views/pages/user-account/ExitUser.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/UserController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/user/UserInfoController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/CarBatteryAndChargerSpeedUpdateDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/CarInfoUpdateDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/userinfo/UserCarInfoDTO.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserService.java
  ifive/src/main/java/kr/co/milionvolt/ifive/service/user/UserServiceImpl.java
Labels: enhancement, Feature

#73 fix : 예약 벌금 알림 기능 에러 처리
  frontend/src/components/Header.vue
  frontend/src/stores/webSocketAlarmStore.js
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/AlarmWebSocketHandler.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/ChargeStateChangeWebSocketHandler.java
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/ChargingWebSocketHandler.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/PayPriceTests.java
Labels: bug

#75 fix : 예약종료시 웹소켓 및 스케쥴러 동작 에러 수정
  frontend/src/components/Header.vue
  frontend/src/stores/webSocketAlarmStore.js
  frontend/src/stores/webSocketChargingStore.js
  frontend/src/views/payment/PayPrice.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/websocket/ChargingWebSocketHandler.java
Labels: bug

#76 Fix: 메인 에러-1
  frontend/src/components/Sidebar.vue
Labels: bug

#79 Fix: main에서 충전기 total 불러올 수 있게 쿼리 수정
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
Labels: bug, enhancement

#80 fix : 웹소켓을 이용한 충전 완료 시 또는 예약 종료로 충전 종료시 타이머는 계속 동작하는 에러 처리
  frontend/src/components/Header.vue
  frontend/src/stores/webSocketChargingStore.js
  frontend/src/views/chargingwebsocket/ChargingStatus.vue
  frontend/src/views/payment/PayPrice.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/payment/PayPriceController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/domain/payment/PayPriceDTO.java
  ifive/src/test/java/kr/co/milionvolt/ifive/mapper/PayPriceTests.java
Labels: bug

#81 Feat: 메인 사이드바 수정 완료
  frontend/src/components/Sidebar.vue
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/ChargingStationMapper.java
Labels: Feature

#82 Refactor: 예약페이지 달력 변경 및 유효성검사 재구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.js
  frontend/src/views/payment/Reservation.vue
  frontend/yarn.lock
  ifive/src/main/java/kr/co/milionvolt/ifive/controller/reservation/ReservationListController.java
  ifive/src/main/java/kr/co/milionvolt/ifive/mapper/UserMapper.java
Labels: enhancement
